### ISSUE TITLE
New version of Sandbox application - what to do in Github?

### ISSUE THREAD

**Issue by RasmusRPaulsen** [thomwolf/GreatSand#35]
Hi,
I have now created an application based on Magic-Sand. There is a significant amount of changes. While I do believe that some of the improvements are usable in Magic-Sand I also think that not all features will/should find their way back into Magic-Sand.

I would like to put it back on Github but I am in doubt about how since I am not experienced in Github or the etiquette here. I see two approaches:

1) I fork Magic-Sand, rename the fork to DuneGames, add my files and deletes unused files.
2) I create a new repo and put DuneGames there, while stating clearly where it is derived from.

Personally, I prefer option 1) to keep in touch with the Magic-Sand original.

Let me know what you recommend. If you prefer direct conversation I can be reached at 
rapa at dtu dot dk

Best,
Rasmus

Major differences between DuneGames and Magic Sand

* Different application logic
 - DuneGames starts in a setup-mode to make sure the Kinect is running before anything else is done (due to major USB related issues on Windows)

* Disabled auto-ROI detection (due to major stability issues)

* Added mouse based point and drag ROI selection

* Added temporal filtering to RGB image stream to avoid rolling-shutter effects

* Updated chessboard calibration procedure

* Added a lot of Debug checks and posibility to dump debug images
 - computes reprojection error to see if the overall calibration is valid

* Added a status-GUI panel to see if the kinect is running and so on

* Several GUI related changes

* Broke the style-convention in particular scope styles

* Added a complete "shape an Island" game

* Changed the name of the application to DuneGames and created new icon

* Build files for Windows enables Win64 builds (VS 2015)

* Did not update Mac build files

**Comment by trueproductions** [comment]
Looking forward to trying it out! you said you didn't make a Mac version yet?

**Comment by RasmusRPaulsen** [comment]
Cool :)
I will put it on Github in the coming week. 
No, I did not update the Mac build files - simply because I am not a Mac user. I do believe that it should compile and run right away if you update the Mac build files. I dont think I have added any Windows specific source.

**Comment by trueproductions** [comment]
Ok. Not sure if I'll be able to compile it, but let me know when the windows version is ready.

-------
In Your Service,

Anthony Cassara | President

True Productions
2001 S. Halsted Street, First Floor
Chicago, IL 60607

Office: 630.325.8030
Cell: 630.816.0106
anthony@trueproductions.com<mailto:anthony@trueproductions.com>
www.trueproductions.com<http://www.trueproductions.com>

On Jul 25, 2017, at 2:18 AM, RasmusRPaulsen <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool :)
I will put it on Github in the coming week.
No, I did not update the Mac build files - simply because I am not a Mac user. I do believe that it should compile and run right away if you update the Mac build files. I dont think I have added any Windows specific source.

-
